testovac/submit/urls.py
from django.conf.urls import url
from django.utils.module_loading import import_string

from . import settings as submit_settings
from .views import view_submit, receive_protocol, download_submit, download_review, get_receiver_templates, get_schema
from .commands import rejudge_submit


urlpatterns = [
    url(r'^post/(?P<receiver_id>\d+)/$',
        import_string(submit_settings.SUBMIT_POST_SUBMIT_FORM_VIEW).as_view(),
        name='post_submit'),
    url(r'^view/(?P<submit_id>\d+)/$', view_submit, name='view_submit'),
    url(r'^download/submit/(?P<submit_id>\d+)/$', download_submit, name='download_submit'),
    url(r'^download/review/(?P<review_id>\d+)/$', download_review, name='download_review'),
    url(r'^receive_protocol/$', receive_protocol),

    url(r'^commands/rejudge/submit/(?P<submit_id>\d+)/$', rejudge_submit, name='rejudge_submit'),

    # This the url path for this command is currently deactivated.
    # Also the button at submit_list template is hidden to prevent misclicks that could cause a judge overflow.
    # TODO: Implement pop-up / confirmation page for resubmit approval
    #url(r'^commands/rejudge/receiver/(?P<receiver_id>\d+)/$', rejudge_receiver_submits, name='rejudge_receiver_submits'),

    url(r'^ajax/get_receiver_templates/', get_receiver_templates),
    url(r'^ajax/get_schema/$', get_schema)
]

testovac/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.views.static import serve

from wiki.urls import get_pattern as get_wiki_pattern
from django_nyt.urls import get_pattern as get_nyt_pattern
import news.urls

import testovac.login.urls
import testovac.tasks.urls
import testovac.submit.urls
import testovac.results.urls
from testovac.admin import admin_site_custom_index_view


def create_custom_admin_urls(urls):
    def get_admin_urls():
        return [
            url(r'^$', admin.site.admin_view(admin_site_custom_index_view))
        ] + urls
    return get_admin_urls

admin.site.get_urls = create_custom_admin_urls(admin.site.get_urls())


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tasks/', include(testovac.tasks.urls)),
    url(r'^news/', include(news.urls)),
    url(r'^submit/', include(testovac.submit.urls)),
    url(r'^results/', include(testovac.results.urls)),
    url(r'^login/', include(testovac.login.urls)),
]

urlpatterns += [
    url(r'^notifications/', get_nyt_pattern()),
    url(r'^$', lambda r: HttpResponseRedirect('wiki/'), name='root'),
    url(r'^wiki/', get_wiki_pattern()),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

testovac/submit/models.py
import os

from django.conf import settings as django_settings
from django.contrib.postgres.fields import JSONField
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.module_loading import import_string
from django.utils.translation import ugettext_lazy as _


from . import settings as submit_settings
from . import constants


class SubmitConfig(models.Model):
    """
    This is an abstract model providing JSONField to store submit configurations.
    """
    configuration = JSONField(default=dict)

    class Meta:
        abstract = True


@python_2_unicode_compatible
class SubmitReceiverTemplate(SubmitConfig):
    """
    When creating a new submit receiver user can choose a template.
    """
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = 'submit receiver template'
        verbose_name_plural = 'submit receiver templates'

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class SubmitReceiver(SubmitConfig):
    """
    Submit receiver manages one type of submits belonging to 1 Submit Receiver Group.
    """
    class Meta:
        verbose_name = 'submit receiver'
        verbose_name_plural = 'submit receivers'

    def can_post_submit(self, user):
        return import_string(submit_settings.SUBMIT_CAN_POST_SUBMIT)(self, user)

    def has_admin_privileges(self, user):
        return import_string(submit_settings.SUBMIT_HAS_ADMIN_PRIVILEGES_FOR_RECEIVER)(self, user)

    def __str__(self):
        return import_string(submit_settings.SUBMIT_DISPLAY_SUBMIT_RECEIVER_NAME)(self)


@python_2_unicode_compatible
class Submit(models.Model):
    """
    Submit holds information about user-submitted data.
    """
    receiver = models.ForeignKey(SubmitReceiver)
    user = models.ForeignKey(django_settings.AUTH_USER_MODEL)
    time = models.DateTimeField(auto_now_add=True)
    filename = models.CharField(max_length=128, blank=True)

    NOT_ACCEPTED = 0
    ACCEPTED_WITH_PENALIZATION = 1
    ACCEPTED = 2
    IS_ACCEPTED_CHOICES = [
        (NOT_ACCEPTED, _('no')),
        (ACCEPTED_WITH_PENALIZATION, _('with penalization')),
        (ACCEPTED, _('yes')),
    ]
    is_accepted = models.IntegerField(default=ACCEPTED, choices=IS_ACCEPTED_CHOICES)

    def dir_path(self):
        return os.path.join(submit_settings.SUBMIT_PATH, 'submits',
                            str(self.user.id), str(self.receiver.id), str(self.id))

    def file_path(self):
        return os.path.join(self.dir_path(), str(self.id) + constants.SUBMITTED_FILE_EXTENSION)

    def file_exists(self):
        return os.path.exists(self.file_path())

    def last_review(self):
        return self.review_set.order_by('-time', '-pk').first()

    def get_absolute_url(self):
        return reverse('view_submit', kwargs=dict(submit_id=self.id))

    class Meta:
        verbose_name = 'submit'
        verbose_name_plural = 'submits'

    def __str__(self):
        return '%s - <%s> (%s)' % (
            self.user,
            self.receiver,
            self.time.strftime('%H:%M:%S %d.%m.%Y'),
        )


@python_2_unicode_compatible
class Review(models.Model):
    """
    Holds information about feedback for one submit. This feedback can be created manually or automatically.
    """
    submit = models.ForeignKey(Submit)
    score = models.FloatField()
    time = models.DateTimeField(auto_now_add=True)
    short_response = models.CharField(max_length=128, blank=True)
    comment = models.TextField(blank=True)
    filename = models.CharField(max_length=128, blank=True)

    def display_score(self):
        return import_string(submit_settings.SUBMIT_DISPLAY_SCORE)(self)

    def verbose_response(self):
        return constants.ReviewResponse.verbose(self.short_response)

    def file_path(self):
        return os.path.join(self.submit.dir_path(), str(self.id) + constants.REVIEWED_FILE_EXTENSION)

    def file_exists(self):
        return os.path.exists(self.file_path())

    def raw_path(self):
        return os.path.join(self.submit.dir_path(), str(self.id) + constants.TESTING_RAW_EXTENSION)

    def protocol_path(self):
        return os.path.join(self.submit.dir_path(), str(self.id) + constants.TESTING_PROTOCOL_EXTENSION)

    def protocol_exists(self):
        return os.path.exists(self.protocol_path())

    class Meta:
        verbose_name = 'review'
        verbose_name_plural = 'reviews'

    def __str__(self):
        return 'review %d for submit %s' % (self.id, str(self.submit))

testovac/submit/forms.py
import os

from django import forms
from django.utils.translation import ugettext_lazy as _

from . import constants
from . import settings as submit_settings
from .submit_helpers import add_language_preference_to_filename


class FileSubmitForm(forms.Form):
    """
    Reusable form for file uploading.
    Constructor takes additional keyword argument 'configuration' - a dict with parameters.
    """
    def __init__(self, *args, **kwargs):
        config = kwargs.pop('configuration')
        super(FileSubmitForm, self).__init__(*args, **kwargs)

        self.extensions = config.get('extensions', None)
        self.languages = config.get('languages', None)

        if self.languages is not None:
            automatic = [[constants.DEDUCE_LANGUAGE_AUTOMATICALLY_OPTION, constants.DEDUCE_LANGUAGE_AUTOMATICALLY_VERBOSE]]
            self.fields['language'] = forms.ChoiceField(label=_('Language'),
                                                        choices=automatic + self.languages,
                                                        required=True)

    submit_file = forms.FileField(
        max_length=submit_settings.SUBMIT_UPLOADED_FILENAME_MAXLENGTH,
        allow_empty_file=True,
    )

    def clean_submit_file(self):
        sfile = self.cleaned_data.get('submit_file', None)
        if sfile:
            extension = os.path.splitext(sfile.name)[1].lower()
            if self.extensions is not None and extension not in self.extensions:
                raise forms.ValidationError(_('Invalid file extension %(extension)s'),
                                            code='invalid extension',
                                            params={'extension': extension})
            return sfile
        else:
            raise forms.ValidationError(_('No file was submitted'), code='no file')

    def clean(self):
        if 'submit_file' in self.cleaned_data and 'language' in self.cleaned_data and self.languages is not None:
            filename = self.cleaned_data['submit_file'].name
            language = self.cleaned_data['language']
            allowed_languages = map(lambda choice: choice[0], self.languages)

            try:
                self.cleaned_data['submit_file'].name = add_language_preference_to_filename(filename, language, allowed_languages)
            except Exception:
                raise forms.ValidationError(_('Automatic language discovery failed. Unknown language extension.'),
                                            code='invalid language')

testovac/submit/views.py
import urllib.parse

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils.html import format_html
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .constants import JudgeTestResult, ReviewResponse
from .models import SubmitReceiverTemplate, SubmitReceiver, Submit, Review
from .forms import FileSubmitForm
from .submit_helpers import create_submit, write_chunks_to_file, send_file
from .judge_helpers import create_review_and_send_to_judge, parse_protocol, JudgeConnectionError


class PostSubmitForm(View):
    login_required = True

    def is_submit_accepted(self, submit):
        """
        Override this method to decide which submits will be accepted, penalized or not accepted.
        This method is called after the submit is created, but before it is saved in database.
        E.g. submits after deadline are not accepted.
        """
        return Submit.ACCEPTED

    def get_success_message(self, submit):
        """
        This message will be added to `messages` after successful submit.
        """
        if submit.receiver.configuration.get('send_to_judge', False):
            return format_html(
                    _('Submit successful. Testing protocol will be soon available <a href="{link}">here</a>.'),
                    link=reverse('view_submit', args=[submit.id])
            )
        return _('Submit successful.')

    def send_to_judge(self, submit):
        create_review_and_send_to_judge(submit)

    def post(self, request, receiver_id):
        receiver = get_object_or_404(SubmitReceiver, pk=receiver_id)
        config = receiver.configuration

        if not receiver.can_post_submit(request.user):
            raise PermissionDenied()

        if 'form' in config:
            form = FileSubmitForm(request.POST, request.FILES, configuration=config['form'])
        else:
            raise PermissionDenied()

        if form.is_valid():
            submit = create_submit(user=request.user,
                                   receiver=receiver,
                                   is_accepted_method=self.is_submit_accepted,
                                   sfile=request.FILES['submit_file'],
                                   )
        else:
            for field in form:
                for error in field.errors:
                    messages.add_message(request, messages.ERROR, u"%s: %s" % (field.label, error))
            for error in form.non_field_errors():
                messages.add_message(request, messages.ERROR, error)
            return redirect(request.POST['redirect_to'])

        if config.get('send_to_judge', False):
            try:
                self.send_to_judge(submit)
            except JudgeConnectionError:
                messages.add_message(request, messages.ERROR, _('Upload to judge was not successful.'))
                return redirect(request.POST['redirect_to'])

        messages.add_message(request, messages.SUCCESS, self.get_success_message(submit))
        return redirect(request.POST['redirect_to'])


@login_required
def view_submit(request, submit_id):
    submit = get_object_or_404(Submit.objects.select_related('receiver'), pk=submit_id)
    user_has_admin_privileges = submit.receiver.has_admin_privileges(request.user)

    if submit.user != request.user and not user_has_admin_privileges:
        raise PermissionDenied()

    conf = submit.receiver.configuration
    review = submit.last_review()
    data = {
        'submit': submit,
        'review': review,
        'user_has_admin_privileges': user_has_admin_privileges,
        'show_submitted_file': conf.get('show_submitted_file', False),
        'protocol_expected': conf.get('send_to_judge', False),
    }

    if data['show_submitted_file']:
        with open(submit.file_path(), 'r') as submitted_file:
            data['submitted_file'] = submitted_file.read().decode('utf-8', 'replace')

    if data['protocol_expected'] and review and review.protocol_exists():
        force_show_details = conf.get('show_all_details', False) or user_has_admin_privileges
        data['protocol'] = parse_protocol(review.protocol_path(), force_show_details)
        data['result'] = JudgeTestResult

    return render(request, 'submit/view_submit.html', data)


@login_required
def download_submit(request, submit_id):
    submit = get_object_or_404(Submit.objects.select_related('receiver'), pk=submit_id)
    if submit.user != request.user and not submit.receiver.has_admin_privileges(request.user):
        raise PermissionDenied()
    return send_file(request, submit.file_path(), submit.filename)


@login_required
def download_review(request, review_id):
    review = get_object_or_404(Review.objects.select_related('submit', 'submit__receiver'), pk=review_id)
    if review.submit.user != request.user and not review.submit.receiver.has_admin_privileges(request.user):
        raise PermissionDenied()
    return send_file(request, review.file_path(), review.filename)


@csrf_exempt
@require_POST
def receive_protocol(request):
    """
    Receive protocol from judge via POST and save it to review.protocol_path()
    """
    review_id = request.POST['submit_id']
    review = get_object_or_404(Review, pk=review_id)
    protocol = request.POST['protocol'].encode('utf-8')
    write_chunks_to_file(review.protocol_path(), protocol)

    protocol_data = parse_protocol(review.protocol_path())
    if protocol_data['ready']:
        review.score = protocol_data['score']
        review.short_response = protocol_data['final_result']
    else:
        review.short_response = ReviewResponse.PROTOCOL_CORRUPTED
    review.save()

    return HttpResponse("")


@login_required
def get_receiver_templates(request):
    """
    Send receiver templates to JavaScript at page admin:submit_submitreceiver_change/add
    """
    if not request.user.is_staff:
        raise PermissionDenied()
    templates = SubmitReceiverTemplate.objects.all()
    templates = {template.id: template.configuration for template in templates}
    return JsonResponse(templates)

testovac/submit/templates/submit/base.html
{% comment %}
  This template serves as an intermediary intended for easier
  incorporation of the provided submit-views and submit-templates into a
  project. The templates used by submit-views all extend this base.
{% endcomment %}

testovac/submit/templates/submit/protocol.html
{% load i18n %}
{% load submit_parts %}

{% if not protocol or not protocol.ready %}
    <div class="alert alert-info">
        <span class="glyphicon glyphicon-refresh glyphicon-animate-rotate"></span>
        {% trans 'Protocol is not available.'%}
    </div>
{% else %}
    {% if protocol.compile_log_present %}
        <h4>{% trans 'Compiler output' %}</h4>
        <pre>{{ protocol.compile_log }}</pre>
    {% endif %}
    {% if protocol.have_tests %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>{% trans 'Test case' %}</th>
                    <th>{% trans 'Result' %}</th>
                    <th>{% trans 'Run time' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for test in protocol.tests %}
                    <tr class="{% if test.result == result.OK %}
                                    success
                               {% elif test.result == result.IGNORED %}
                                    warning
                               {% else %}
                                    danger
                               {% endif %}">
                        <td>{{ test.name }}
                            {% if test.show_details %}
                                <a class="pull-right" data-toggle="collapse" href="#collapse{{ forloop.counter0 }}">{% trans 'Show details' %}</a>
                            {% endif %}
                        </td>
                        <td><span data-toggle="tooltip" data-placement="auto" title="{{ test.result }}">{{ result|verbose:test.result }}</span></td>
                        <td>{{ test.time }} ms</td>
                    </tr>

                    {% if test.show_details %}
                        <tr>
                            <td colspan="3"  style="padding:0">
                                <div class="collapse" id="collapse{{ forloop.counter0 }}"> {{ test.details|linebreaksbr }}</div>
                            </td>
                        </tr>
                       {% endif %}
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endif %}

testovac/submit/templates/submit/review_info.html
{% load i18n %}

<div class="panel panel-default">
    <div class="panel-heading">{% trans 'Review' %}</div>
    <div class="panel-body">
        {% if review %}
            <table class="table-condensed">
                <tr>
                    <th>{% trans 'Result' %}:</th>
                    <td>{{ review.verbose_response }}</td>
                </tr>
                <tr>
                    <th>{% trans 'Score' %}:</th>
                    <td>{{ review.display_score }}</td>
                </tr>
                {% if review.file_exists %}
                    <tr>
                        <th>{% trans 'Reviewed file' %}:</th>
                        <td><a href="{% url 'download_review' review.id %}">{{ review.filename }}</a></td>
                    </tr>
                {% endif %}
                {% if review.comment %}
                    <tr>
                        <th>{% trans "Reviewer's comment" %}:</th>
                        <td></td>
                    </tr>

                {% endif %}
            </table>
            {% if review.comment %}
                <p>{{ review.comment|linebreaks }}</p>
            {% endif %}
        {% else %}
            <p>{% trans 'Not reviewed yet.' %}</p>
        {% endif %}
    </div>
</div>

testovac/submit/templates/submit/submit_info.html
{% load i18n %}

<div class="panel panel-default">
    <div class="panel-heading">{% trans 'Submit' %}</div>
    <div class="panel-body">
    <table class="table-condensed">
        <tr>
            <th>ID:</th>
            <td>{{ submit.id }}</td>
        </tr>
        <tr>
            <th>{% trans 'User' %}:</th>
            <td>{{ submit.user }}</td>
        </tr>
        <tr>
            <th>{% trans 'Time' %}:</th>
            <td>{{ submit.time }}</td>
        </tr>
        <tr>
            <th>{% trans 'Accepted' %}:</th>
            <td>{{ submit.get_is_accepted_display }}</td>
        </tr>
        {% if submit.file_exists %}
            <tr>
                <th>{% trans 'Submitted file' %}:</th>
                <td>{{ submit.filename }}</td>
            </tr>
            <tr>
                <th></th>
                <td>
                    {% if show_submitted_file %}
                        <a class="btn btn-primary" data-toggle="collapse" href="#collapse-submitted-file">{% trans 'Show' %}</a>
                    {% endif %}
                     <a class="btn btn-primary" href="{% url 'download_submit' submit.id %}">{% trans 'Download' %}</a>
                </td>
            </tr>
        {% endif %}
    </table>
    </div>
</div>

testovac/submit/templates/submit/view_submit.html
{% extends "submit/base.html" %}

{% load submit_parts %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans 'Submit' %} {{ submit.id }}{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'submit/google-code-prettify/prettify.css' %}" type="text/css" />
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'submit/google-code-prettify/prettify.js' %}" type="text/javascript"></script>
    <script>
        !function ($) {
            $(function(){
            window.prettyPrint && prettyPrint()
            })
        }(window.jQuery)
    </script>
{% endblock %}

{% block page_header %}
    <h1>{% trans 'Submit details' %}</h1>

    {% if user_has_admin_privileges %}
        <a href="{% url 'admin:submit_submit_change' submit.id %}">
            <span class="glyphicon glyphicon-pencil"></span> {% trans 'Edit and review' %}
        </a>
        {% if submit.receiver.configuration.send_to_judge %}
            <a href="{% url 'rejudge_submit' submit.id %}">
                <span class="glyphicon glyphicon-send"></span> {% trans 'Rejudge submit' %}
            </a>
        {% endif %}
    {% endif %}
{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col col-md-6">
            {% include 'submit/submit_info.html' %}
        </div>
        <div class="col col-md-6">
            {% include 'submit/review_info.html' %}
        </div>
    </div>

    {% if show_submitted_file %}
        <pre class="prettyprint collapse" id="collapse-submitted-file">{{ submitted_file }}</pre>
    {% endif %}

    {% if review and protocol_expected %}
        <h3>{% trans 'Protocol' %}</h3>
        {% include 'submit/protocol.html' %}
    {% endif %}

    <h3>{% trans 'All submits' %}</h3>
    {% submit_list submit.receiver submit.user %}
{% endblock page_content %}